src/Entity/Table.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TableRepository")
 * @ORM\Table(name="_table")
 */
class Table
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $coord_x;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $coord_y;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Restaurant", inversedBy="tables")
     * @ORM\JoinColumn(nullable=false)
     */
    private $restaurant;

    /**
     * @ORM\OneToMany(targetEntity="Commande", mappedBy="table", cascade={"remove"})
     */
    private $commandes;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $numero;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_delete;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
        $this->is_delete = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom()
    {
        return $this->nom;
    }

    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCoordX()
    {
        return $this->coord_x;
    }

    public function setCoordX($coord_x)
    {
        $this->coord_x = $coord_x;

        return $this;
    }

    public function getCoordY()
    {
        return $this->coord_y;
    }

    public function setCoordY($coord_y)
    {
        $this->coord_y = $coord_y;

        return $this;
    }

    public function getRestaurant()
    {
        return $this->restaurant;
    }

    public function setRestaurant($restaurant)
    {
        $this->restaurant = $restaurant;

        return $this;
    }

    public function __toString(){
        return $this->nom;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setTable($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->contains($commande)) {
            $this->commandes->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getTable() === $this) {
                $commande->setTable(null);
            }
        }

        return $this;
    }

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function setNumero(?int $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getIsDelete(): ?bool
    {
        return $this->is_delete;
    }

    public function setIsDelete(?bool $is_delete): self
    {
        $this->is_delete = $is_delete;

        return $this;
    }
}

src/Form/TableType.php
<?php

namespace App\Form;

use App\Entity\Table;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TableType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('description')
            ->add('coord_x', null, ['required' => false])
            ->add('coord_y', null, ['required' => false])
            ->add('numero')
            ->add('restaurant')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Table::class,
        ]);
    }
}

src/Controller/Api/TableController.php
<?php

namespace App\Controller\Api;

use App\Entity\Table;
use App\Repository\TableRepository;
use App\Repository\RestaurantRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\Controller\Annotations as Rest;

/**
 * API Controller.
 * @Route("/api/table", name="api_table_")
 */
class TableController extends APIController
{
    private $tableRepository;
    private $restaurantRepository;
    private $doctrine;

    public function __construct(TableRepository $tableRepository, RestaurantRepository $restaurantRepository)
    {
        $this->tableRepository = $tableRepository;
        $this->restaurantRepository = $restaurantRepository;
    }

    /**
    * Get table by shop
    * @Rest\Get("/get-by-shop", name="get_by_shop")
    *
    * @return Response
    */
    public function getAllTableOfMyShop(Request $request)
    {
        $user = $this->authToken($request);
        if (is_array($user)) {
            return $this->handleView(
                $this->view(
                    $user,
                    Response::HTTP_UNAUTHORIZED)
            );
        }

        $tables = $this->tableRepository->findBy(['restaurant'=>$user->getRestaurant()->getId()]);
        $tablesArray = [];
        foreach ($tables as $key => $value) {
            $tablesArray[] = [
                'id'=>$value->getId(),
                'name'=> $value->getNom(),
                'description'=> $value->getDescription(),
                'coord_x'=> $value->getCoordX(),
                'coord_y'=> $value->getCoordY(),
                'commandes'=> count($value->getCommandes())
            ];
        }

        return $this->handleView($this->view(
            $tablesArray, 
            Response::HTTP_OK)
        );
    }

    /**
     * @Rest\Post("/add", name="add_table")
     *
     * @return Response
     */
    public function addTable(Request $request)
    {
        $user = $this->authToken($request);
        if (is_array($user)) {
            return $this->handleView(
                $this->view(
                    $user,
                    Response::HTTP_UNAUTHORIZED)
            );
        }

        $entityManager = $this->getDoctrine()->getManager();

        $table = new Table();
        if($request->get('table_id'))
            $table = $this->tableRepository->find($request->get('table_id'));

        $table->setNom($request->get('nom'));
        $table->setDescription($request->get('description'));
        $table->setNumero($request->get('numero'));
        $table->setRestaurant($this->restaurantRepository->find($user->getRestaurant()->getId()));
        
        $entityManager->persist($table);
        $entityManager->flush();

        return $this->handleView($this->view(
            $table->getId(), 
            Response::HTTP_OK)
        );
    }

}

src/Controller/TableController.php
<?php

namespace App\Controller;

use App\Entity\Table;
use App\Form\TableType;
use App\Repository\TableRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/dashboad/table")
 */
class TableController extends AbstractController
{
    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @Route("/", name="table_index", methods={"GET"})
     */
    public function index(TableRepository $tableRepository): Response
    {   
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user = $this->getUser();
        if($user->getRole() == "superadmin")
            $tables = $tableRepository->findAll();
        elseif($this->getUser()->getRole() == "admin")
            $tables = $tableRepository->findBy(['restaurant'=>$user->getRestaurant()]);

        return $this->render('table/index.html.twig', [
            'tables' => $tableRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="table_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {   
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $table = new Table();
        $form = $this->createForm(TableType::class, $table);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $user = $this->security->getUser();
            $table->setRestaurant($user->getRestaurant());
            $entityManager->persist($table);
            $entityManager->flush();

            return $this->redirectToRoute('table_index');
        }

        return $this->render('table/new.html.twig', [
            'table' => $table,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="table_show", methods={"GET"})
     */
    public function show(Table $table): Response
    {   
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        return $this->render('table/show.html.twig', [
            'table' => $table,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="table_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Table $table): Response
    {   
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $form = $this->createForm(TableType::class, $table);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('table_index');
        }

        return $this->render('table/edit.html.twig', [
            'table' => $table,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="table_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Table $table): Response
    {   
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        if ($this->isCsrfTokenValid('delete'.$table->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($table);
            $entityManager->flush();
        }

        return $this->redirectToRoute('table_index');
    }
}

templates/table/_delete_form.html.twig
<form method="post" action="{{ path('table_delete', {'id': table.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ table.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/table/_form.html.twig
{{ form_start(form) }}
	<div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>

    <div class="item form-group">
        <label class="col-form-label col-md-3 col-sm-3 label-align" for="name">Nom <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6">
        	{{ form_widget(form.nom, { 'attr': {'class': 'form-control', 'required':'required'} }) }}
        </div>
    </div>
    <div class="item form-group">
        <label class="col-form-label col-md-3 col-sm-3 label-align" for="email">Description <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6">
	        {{ form_widget(form.description, { 'attr': {'class': 'form-control'}} ) }}
	    </div>
    </div>
    <div class="item form-group">
        <label class="col-form-label col-md-3 col-sm-3 label-align" for="email">coord X <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6">
	        {{ form_widget(form.coord_x, { 'attr': {'class': 'form-control'}} ) }}
	    </div>
    </div>
    <div class="item form-group">
        <label class="col-form-label col-md-3 col-sm-3 label-align" for="email">coord Y <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6">
	        {{ form_widget(form.coord_y, { 'attr': {'class': 'form-control'}} ) }}
	    </div>
    </div>
    <div class="item form-group">
        <label class="col-form-label col-md-3 col-sm-3 label-align" for="email">Numero <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6">
            {{ form_widget(form.numero, { 'attr': {'class': 'form-control', 'required':'required'}} ) }}
        </div>
    </div>
    <div class="item form-group">
        <label class="col-form-label col-md-3 col-sm-3 label-align" for="email">Restaurant<span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6">
            {{ form_widget(form.restaurant, { 'attr': {'class': 'form-control', 'required':'required'}} ) }}
        </div>
    </div>
    <div class="ln_solid"></div>
	<div class="form-group">
		<div class="offset-md-3">
		  <button class="btn call-action">{{ button_label|default('Enregistrer') }}</button>
		</div>
	</div>
{{ form_end(form) }}

templates/table/edit.html.twig
{% extends 'backOffice/layout.html.twig' %}

{% block title %}{{parent()}} | edition d'une table{% endblock %}
{% block datatables_css %}{% endblock %}

{% block bo_content %}
    <div class="row-title">
        <h1 class="title">Edition d'une table</h1> 
        <a href="{{path('table_index')}}" class="call-action btn">Liste tables</a>
    </div>
    <div class="x_panel">
        <div class="x_content">

		    {{ include('table/_form.html.twig', {'button_label': 'Modifier'}) }}
			<div class="offset-md-3 btn-dlt-p-edit">
		    	{{ include('table/_delete_form.html.twig') }}
		    </div>
		</div>
	</div>
{% endblock %}

{% block validation_js %}{% endblock %}
{% block datatables_js %}{% endblock %}

templates/table/index.html.twig
{% extends 'backOffice/layout.html.twig' %}

{% block title %}{{parent()}} | Table{% endblock %}

{% block bo_content %}
    <div class="row-title">
        <h1 class="title">Liste des tables</h1> <a href="{{path('table_new')}}" class="call-action btn">Nouveau table</a>
    </div>
    <div class="x_panel">
        <div class="x_content">
            <div class="card-box table-responsive">
                <table id="datatable-responsive" class="table table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nom</th>
                            <th>Description</th>
                            <th>numero</th>
                            <th>Coord_x</th>
                            <th>Coord_y</th>
                            <th>actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for table in tables %}
                        <tr>
                            <td>{{ table.id }}</td>
                            <td>{{ table.nom }}</td>
                            <td>{{ table.description }}</td>
                            <td>{{ table.numero }}</td>
                            <td>{{ table.coordX }}</td>
                            <td>{{ table.coordY }}</td>
                            <td>
                                <a href="{{ path('table_show', {'id': table.id}) }}">show</a>
                                <a href="{{ path('table_edit', {'id': table.id}) }}">edit</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}
{% block validation_js %}
{% endblock %}

templates/table/new.html.twig
{% extends 'backOffice/layout.html.twig' %}

{% block title %}{{parent()}} | creation de table{% endblock %}
{% block datatables_css %}{% endblock %}

{% block bo_content %}
    <div class="row-title">
        <h1 class="title">Nouveau table</h1> <a href="{{path('table_index')}}" class="call-action btn">Liste table</a>
    </div>
    <div class="x_panel">
        <div class="x_content">
    	{{ include('table/_form.html.twig') }}
	    </div>
	</div>
{% endblock %}

templates/table/show.html.twig
{% extends 'backOffice/layout.html.twig' %}

{% block title %}{{parent()}} | Table{% endblock %}

{% block datatables_css %}{% endblock %}

{% block bo_content %}
    <div class="row-title">
        <h1 class="title">Tables</h1> <a href="{{path('table_index')}}" class="call-action btn">Liste tables</a>
    </div>
    <div class="x_panel">
        <div class="x_content">
            <table class="table">
                <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ table.id }}</td>
                    </tr>
                    <tr>
                        <th>Nom</th>
                        <td>{{ table.nom }}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{ table.description }}</td>
                    </tr>
                    <tr>
                        <th>Numero</th>
                        <td>{{ table.numero }}</td>
                    </tr>
                    <tr>
                        <th>Coord_x</th>
                        <td>{{ table.coordX }}</td>
                    </tr>
                    <tr>
                        <th>Coord_y</th>
                        <td>{{ table.coordY }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="detail-group-btn">
        <a href="{{ path('table_edit', {'id': table.id}) }}" class="btn call-action">Modifier</a>
        {{ include('table/_delete_form.html.twig') }}
    </div>
{% endblock %}

{% block validation_js %}{% endblock %}
{% block datatables_js %}{% endblock %}